name: SQEmpire
version: 3.1.33
description: StarQuest Empires!
author: dibujaron
website: http://starquestminecraft.com
main: com.whirlwindgames.dibujaron.sqempire.SQEmpire
depend: [Movecraft, Vault, WorldGuard]

commands:
   empire:
      description: empire master command.
      usage: Do /empire join
   playersendempire:
      description: sends player to empire spawn.
      usage: /playersendempire <player>
   empirereset:
      description: reset a player's empire.
      usage: /empirereset <player>
   setdominantempire:
      description: used for interserver communication
permissions:
   SQEmpire.manageControlPoints:
      description: permission node for managing control points
      default: op
   SQEmpire.reloadEmpire:
      description: permission node for reloading empires
      default: op
